// Generated by https://quicktype.io

export interface ILicense {
    detailsUrl?:            URL;
    isDeprecatedLicenseId?: boolean;
    isDsiApproved?:         boolean;
    licenseId?:             string;
    name?:                  string;
    reference?:             string;
    referenceNumber?:       number;
    seeAlso?:               URL[];
}

export const licenses:ILicense[] = require("../database/licensesDb.json");